config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :stories
    
    root "stories#index"

end

app/models/story.rb
class Story < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
	before_action :find_story, only: [:show, :edit, :update, :destroy]

    def index
    	@stories = Story.all.order("created_at DESC")
        for story in @stories
            if(story.youtube.to_s != '')
                story.youtube = YouTubeAddy.youtube_embed_url(story.youtube, 420, 315).gsub! 'http', 'https'
            end
            if(story.vine.to_s != '')
                story.vine = '<iframe src="' + story.vine + '/embed/simple" width="600" height="600" frameborder="0"></iframe><script src="https://platform.vine.co/static/scripts/embed.js"></script>'
            end
        end
    end
    
    def show
        if @story.youtube.to_s != ''
            @story.youtube = YouTubeAddy.youtube_embed_url(@story.youtube, 840, 630).gsub! 'http', 'https'
        end
        if @story.vine.to_s != ''
            @story.vine = '<iframe src="' + @story.vine + '/embed/simple" width="600" height="600" frameborder="0"></iframe><script src="https://platform.vine.co/static/scripts/embed.js"></script>'
        end
    end
    
    def new
    	@story = current_user.stories.build
    end
    
    def create
    	@story = current_user.stories.build(story_params)

    	if @story.save
    		redirect_to @story, notice: "Succesfully created new Story"
    	else
    		render 'new'
    	end
    end
    
    def edit
    end

    def update
    	if @story.update(story_params)
    		redirect_to @story, notice: "Succesfully updated Story"
    	else
    		render 'edit'
    	end
    end

    def destroy
    	@story.destroy
    	redirect_to root_path
    end

    private

    def story_params
        params.require(:story).permit(:title, :youtube, :vine, :twitter, :description)
    end

    def find_story
    	@story = Story.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
%head
	%title RFE Board
	= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
	= javascript_include_tag 'application', 'data-turbolinks-track' => true
	= csrf_meta_tags
%body
	%nav.navbar.navbar-default
		.container
			.navbar-brand= link_to "RFE Board", root_path

			- if user_signed_in?
				%ul.nav.navbar-nav.navbar-right
					%li.black= link_to "New Post", new_story_path, :class=>"black"
					%li.black= link_to "Account", edit_user_registration_path
					%li.black= link_to "Sign Out", destroy_user_session_path, method: :delete
			- else
				%ul.nav.navbar-nav.navbar-right
					%li= link_to "Sign Up", new_user_registration_path
					%li= link_to "Sign In", new_user_session_path
	.container
		- flash.each do |name, msg|
			= content_tag :div, msg, class: "alert alert-info"
	= yield

app/views/stories/_form.html.haml
= simple_form_for @story, html: { multipart: true } do |f|
    - if @story.errors.any?
        #errors
            %h2
                = pluralize(@story.errors.count, "error")
                prevented this Story from saving
            %ul
                - @story.errors.full_messages.each do |msg|
                    %li= msg

    .form-group
        = f.input :title, input_html: { class: 'form-control' }
    .form-group
        = f.input :youtube, input_html: { class: 'form-control' }
    .form-group
        = f.input :twitter, input_html: {class: 'form-control'}
        %b
            %i Must be embed code not link
    .form-group
        = f.input :vine, input_html: { class: 'form-control' }
    .form-group
        = f.input :description, input_html: { class: 'form-control' }

    = f.button :submit, class: "btn btn-primary"

app/views/stories/edit.html.haml
#edit_page.col-md-8.col-md-offset-2
	.row
		.panel.panel-default
			.panel-heading
				%h1 Edit Post
			.panel-body
				= render 'form'

app/views/stories/index.html.haml
#stories.transitions-enabled
	- @stories.each do |story|
		.box.panel.panel-default
			- if story.youtube.to_s != ''
				= story.youtube.html_safe
			- if story.twitter.to_s != ''
				.twitter
					= story.twitter.html_safe
			- if story.vine.to_s != ''
				= story.vine.html_safe
			%h2= link_to story.title, story
			%p.user
				Submitted by
				= story.user.email
			

app/views/stories/new.html.haml
.col-md-6.col-md-offset-3
	%h1 New Post

	= render 'form'

	= link_to "Back", root_path

app/views/stories/show.html.haml
#story_show.row
	.col-md-8.col-md-offset-2
		.panel.panel-default
			.panel-heading.story_image
				- if @story.youtube.to_s != ''
					= @story.youtube.html_safe
				- if @story.vine.to_s != ''
					= @story.vine.html_safe
				- if @story.twitter.to_s != ''
					.twitter
						= @story.twitter.html_safe 
			.panel-body
				%h1= @story.title
				%p.description= @story.description
			.panel-footer
				.row
					.col-md-6
						%p.user
							Submitted by
							= @story.user.email
					.col-md-6
						.btn-group.pull-right
							- if user_signed_in?
								= link_to "Edit", edit_story_path, class: "btn btn-default"
								= link_to "Delete", story_path, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"

app/views/sync/stories/_story.html.haml
.box.panel.panel-default
	- if story.youtube.to_s != ''
		= story.youtube.html_safe
	- if story.vine.to_s != ''
		= story.vine.html_safe
	%h2= link_to story.title, story
	%p.user
		Submitted by
		= story.user.email